forum/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.PostList.as_view()),
    path('<int:pk>/', views.PostDetail.as_view()),
    path('create_post/', views.PostCreate.as_view()),
    path('update_post/<int:pk>/', views.PostUpdate.as_view()),
    path('<int:pk>/new_comment/', views.new_comment),
    path('update_comment/<int:pk>/', views.CommentUpdate.as_view()),
    path('delete_comment/<int:pk>/', views.delete_comment),
    # path('<int:pk>/', views.single_post_page),
    # path('', views.index),
]

itm_billiard/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
# from user.views import SocialLoginCallbackView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('forum/', include('forum.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('user.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('', include('dashboard.urls')),
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include

from . import views

urlpatterns = [
    path('<provider>/login/callback', views.social_login),
    path('', include('allauth.urls')),
]

forum/models.py
from django.db import models
from django.contrib.auth.models import User
from markdownx.models import MarkdownxField
from markdownx.utils import markdown

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=30)
    content = MarkdownxField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    author = models.ForeignKey(User, null=True ,on_delete=models.SET_NULL)

    def __str__(self):
        return f'[{self.pk}]{self.title} :: {self.author}'

    def get_absolute_url(self):
        return f'/forum/{self.pk}/'

    def get_content_markdown(self):
        return markdown(self.content)

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(max_length=40)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.author}::{self.content}'

    def get_absolute_url(self):
        return f'{self.post.get_absolute_url()}#comment-{self.pk}'

    def get_avatar_url(self):
        if self.author.socialaccount_set.exists():
            return self.author.socialaccount_set.first().get_avatar_url()
        else:
            return f'https://doitdjango.com/avatar/id/224/fd62aa66379a006e/svg/{self.author.username}@gmail.com/'

forum/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

forum/views.py
from django.contrib.auth.models import Permission
from django.shortcuts import redirect, render
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from .models import Post, Comment
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .forms import CommentForm
from django.shortcuts import get_object_or_404

class PostList(ListView):
    model = Post
    # template_name = 'forum/index.html'
    ordering = '-pk'
    paginate_by = 5

class PostDetail(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data()
        context['comment_form'] = CommentForm
        return context

class PostCreate(CreateView):
    model = Post
    fields = ['title','content']

    def form_valid(self, form):
        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            return super(PostCreate, self).form_valid(form)
        else:
            return redirect('/forum/')

class PostUpdate(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(PostUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

def new_comment(request, pk):
    if request.user.is_authenticated:
        post = get_object_or_404(Post, pk=pk)

        if request.method == 'POST':
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.post = post
                comment.author = request.user
                comment.save()
                return redirect(comment.get_absolute_url())
        else:
            return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = comment.post
    if request.user.is_authenticated and request.user == comment.author:
        comment.delete()
        return redirect(post.get_absolute_url())
    else:
        raise PermissionDenied

class CommentUpdate(LoginRequiredMixin, UpdateView):
    model = Comment
    form_class = CommentForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(CommentUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

forum/templates/forum/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <title>{% block head_title%}Forum{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'forum/bootstrap/bootstrap.min.css' %}" media="screen">
    <!-- <link rel="stylesheet" href="{% static 'forum/css/styles.css' %}"> -->
</head>

<body>
    {% include 'forum/navbar.html' %}

    <div class="container my-3">
        <div class="row">
            <div class="col-12" id="main-area">
                {% block main_area %}
                {% endblock %}
            </div>
        </div>
    </div>

    {% include 'forum/footer.html' %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
        integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
        crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/798b8bea4c.js" crossorigin="anonymous"></script>

    <!-- <script src="https://code.jquery.com/qunit/qunit-2.6.1.js" type="text/javascript"></script> -->
    <script src="{% static 'dashboard/js/jquery.twbsPagination.js' %}" type="text/javascript"></script>

    <script src="{% static 'dashboard/js/scripts.js' %}" type="text/javascript"></script>

</body>

</html>

forum/templates/forum/comment_form.html
{% extends 'forum/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}댓글 수정{% endblock %}

{% block main_area %}
    <h1>댓글 수정</h1>
    <hr/>
    <form method="post" id="comment-form">
        {% csrf_token %}
            {{ form | crispy }}
        <br/>
        <button type="submit" class="btn btn-info float-right">작성하기</button>
    </form>


{% endblock %}
    

forum/templates/forum/footer.html
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">
            <!-- Copyright &copy; Your Website 2021 -->
            contact to developer : <a href="mailto:sung2687@gmail.com">sung2687@gmail.com</a>
        </p>
    </div>
</footer>

forum/templates/forum/index.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <title>Forum</title>
    </head>
    <body>
        <h1>Forum</h1>

    {% for p in post_list %}
        <hr/>
        <h2><a href="{{ p.get_absolute_url }}">{{ p.title }}</a></h2>
        <h4>{{ p.created_at }}</h4>
        <p>{{ p.content }}</p>
    {% endfor %}
    </body>
</html>

forum/templates/forum/navbar.html
{% load socialaccount %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="/">ITM-Billiard</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/forum/">Forum</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {% if user.socialaccount_set.all.0.get_avatar_url %}
                        <img class="rounded-circle" width="25px" src="{{ user.socialaccount_set.all.0.get_avatar_url }}"
                            alt="">
                        {% else %}
                        <img class="rounded-circle" width="25px"
                            src="https://doitdjango.com/avatar/id/224/fd62aa66379a006e/svg/{{self.author.username}}@gmail.com/">
                        {% endif %}
                        &nbsp;
                        {{ user.first_name }}

                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <form method="post" action="{% url 'account_logout' %}">
                            {% csrf_token %}
                            <button class="dropdown-item" type="submit">Log Out</button>
                        </form>

                    </div>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="#" data-toggle="modal" data-target="#loginModal">Log In</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="logInModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="logInModalLabel"><i class="fas fa-sign-in-alt"></i>&nbsp Log In</h5>
                <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <a role="button" class="btn btn-outline-dark btn-block btn-sm"
                            href="{% provider_login_url 'google' %}"><i class="fab fa-google"></i>&nbsp&nbsp Log in with
                            Google</a>

                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <!-- <button type="button" class="btn btn-primary">Save changes</button> -->
            </div>
        </div>
    </div>
</div>

forum/templates/forum/post_detail.html
{% extends 'forum/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}
{{ post.title }} - Blog
{% endblock %}

{% block main_area %}
<div id="post-area">
    {% if user.is_authenticated and user == post.author %}
    <a class="btn btn-info btn-sm float-right" href="/forum/update_post/{{ post.pk }}" role="button"><i
            class="fas fa-pen"> 수정하기</i></a>
    {% endif %}


    <h1>{{ post.title }}</h1>
    <h6>{{ post.author.first_name }}</h6>
    <h5>{{ post.created_at }}</h5>
    <p>{{ post.get_content_markdown | safe }}</p>
</div>
<hr />


<!-- Comment -->
<div class="comment-area">
    <div class="card my-4">
        <h5 class="card-header">댓글 작성</h5>
        <div class="card-body">
            {% if user.is_authenticated %}
            <form id="comment-form" method="POST" action="{{ post.get_absolute_url }}new_comment/">
                {% csrf_token %}
                {{ comment_form | crispy }}
                <button type="submit" class="btn btn-info float-right">작성하기</button>
            </form>
            {% else %}
            <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="#" data-toggle="modal"
                data-target="#loginModal">로그인 후 댓글 작성하기</a>
            {% endif %}
        </div>
    </div>

    {% if post.comment_set.exists %}
    {% for comment in post.comment_set.iterator %}
    <div class="media mb-4" id="comment-{{ comment.pk }}">
        <img class="d-flex mr-3 rounded-circle" src="{{ comment.get_avatar_url }}" alt="{{ comment.author }}"
            width="60px">
        <div class="media-body">
            {% if user.is_authenticated and comment.author == user %}
            <div class="float-right">
                <a role="button" class="btn btn-sm btn-danger mx-2" id="comment-{{comment.pk}}-delete-modal-btn" href="#"
                    data-toggle="modal" data-target="#deleteCommentModal-{{ comment.pk }}">
                    삭제
                </a>
                <a role="button" class="btn btn-sm btn-info float-right" id="comment-{{comment.pk}}-update-btn"
                    href="/forum/update_comment/{{comment.pk}}/">
                    수정
                </a>

            </div>

            <div class="modal fade" id="deleteCommentModal-{{ comment.pk}}" tabindex="-1" role="dialog"
                aria-labelledby="deleteCommentModalLabel" area-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="deleteModalLabel">삭제하시겠습니까?</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <del>{{ comment | linebreaks }}</del>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">취소</button>
                            <a role="button" class="btn btn-danger" href="/forum/delete_comment/{{comment.pk}}/">삭제</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            <h5 class="mt-0">{{ comment.author.first_name }} &nbsp;&nbsp;<small
                    class="text-muted">{{comment.created_at}}</small></h5>
            <p>{{ comment.content | linebreaks }}</p>
            {% if comment.created_at != comment.modified_at %}
            <p class="text-muted float-right"><small>Updated: {{ comment.modified_at }}</small></p>
            {% endif %}

        </div>
    </div>
    {% endfor %}
    {% endif %}
</div>
</hr>

{% endblock %}

forum/templates/forum/post_form.html
{% extends 'forum/base.html' %}
{% load crispy_forms_tags %}
{% block head_title %}Forum{% endblock %}

{% block main_area %}
    <h1>게시글 작성</h1>
    <hr/>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
            {{ form | crispy }}
            <!-- <div id="div_id_tags_str">
                <label for="id_tags_str">Tags:</label>
                <input type="text" name="tags_str" id="id_tags_str" class="textinput textInput form-control">
            </div>
            <br/> -->
        <br/>
        <button type="submit" class="btn btn-info float-right">적용하기</button>
    </form>
    

{% endblock %}
    

forum/templates/forum/post_list.html
{% extends 'forum/base.html' %}

{% block main_area %}

<h2>Forum</h2>
<table class="table table-hover">
  <thead>
    <tr>
      <th>번호</th>
      <th>제목</th>
      <th>작성자</th>
      <th>날짜</th>
      <th>조회수</th>
    </tr>
  </thead>
  <tbody>
    {% if post_list.exists %}
    {% for p in post_list %}
    <tr onClick="location.href='{{ p.get_absolute_url }}'">
      <td>{{ p.pk }}</td>
      <td>{{ p.title }}</td>
      <td>{{ p.author }}</td>
      <td>{{ p.created_at }}</td>
      <td>조회수</td>
    </tr>
    {% endfor %}
    {% else %}
    <h3>아직 게시물이 없습니다.</h3>
    {% endif %}
  </tbody>
</table>

{% if user.is_authenticated %}
<div class="row">
  <a class="btn btn-info btn-sm ml-auto" role="button" href="/forum/create_post">
    <i class="fas fa-pen"></i>
    &nbsp;&nbsp;글 작성
  </a>
</div>
{% endif %}

</hr>

{% if is_paginated %}
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <div class="row">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Next</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
      </li>
      {% endif %}

      <!-- {% for page in page_obj.pagnator.num_pages.iterator %}
      <li class="page-item"><a class="page-link" href="?page={{page}}">{{ page }}</a></li>
      {% endfor %} -->
      {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">Prev</a>
      </li>
      <!-- <li class="page-item"><a class="page-link" href="#">1</a></li>
      <li class="page-item"><a class="page-link" href="#">2</a></li>
      <li class="page-item"><a class="page-link" href="#">3</a></li> -->
      {% else %}
      <li class="page-item disabled">
        <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Prev</a>
      </li>
      {% endif %}
    </div>
  </ul>
  <span class="row current justify-content-center mt-0">
    {{ page_obj.number }} / {{ page_obj.paginator.num_pages }}
  </span>


</nav>
{% endif %}
{% endblock %}

forum/templates/forum/single_post_page.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8">
        <title>{{ post.title }} - Forum</title>
    </head>
    <body>
        <nav>
            <a href="/forum/">Forum</a>
        </nav>

        <h1>{{ post.title }}</h1>
        <h4>{{ post.created_at }}</h4>
        <p>{{ post.content }}</p>
        <hr/>
        <h3>나중에 여기 댓글 기능 추가</h3>
    </body>
</html>