dashboard/urls.py
from django.urls import path
from . import views
# from .views import GameList


urlpatterns = [
    path('create_game/',views.create_game),
    path('', views.GameList.as_view()),
]

itm_billiard/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
# from user.views import SocialLoginCallbackView

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('forum/', include('forum.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('user.urls')),
    path('markdownx/', include('markdownx.urls')),
    path('', include('dashboard.urls')),
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include

from . import views

urlpatterns = [
    path('<provider>/login/callback', views.social_login),
    path('', include('allauth.urls')),
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
# from datetime import date
from django.utils import timezone


class Game(models.Model):
    played_at = models.DateTimeField(auto_now_add=True)
    num_players = models.IntegerField()


# Create your models here.
class Score(models.Model):
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    player = models.ForeignKey(User, on_delete=models.CASCADE)
    score = models.IntegerField()
    win = models.BooleanField()

    class Meta:
        ordering=['win','player']

dashboard/forms.py
from django.forms.widgets import ChoiceWidget
from .models import Game,User
from django import forms
from django.forms import widgets


class GameForm(forms.ModelForm):
    class Meta:
        model = Game
        fields = ('num_players',)

dashboard/views.py
from django.shortcuts import redirect, render
from django.views.generic import ListView
from .forms import GameForm
from .models import Game,User,Score
from django.core.exceptions import PermissionDenied, BadRequest
from django.core.paginator import Paginator

import logging
class PlayerList(ListView):
    model = User
    paginate_by = 5

class GameList(ListView):
    model = Game
    ordering = '-played_at'
    paginated_by = 10

    def get_context_data(self, **kwargs):
        context = super(GameList, self).get_context_data()
        context['user_list'] = User.objects.filter(is_staff=False)
        rank_list = self.get_rank_list()
        
        # p = Paginator[rank_list,5]
        context['rank_list'] = rank_list
        context['n_games'] = Game.objects.all().count  
        context['n_rank'] = len(rank_list)
        # context['player_list'] = PlayerList.as_view()
        return context

    def get_rank_list(self):
        rank = list()
        for user in User.objects.filter(is_staff=False).order_by():
            tmp = {}
            tmp['name'] = user.first_name
            nWins = len(Score.objects.filter(player=user,win=True))
            nGames = len(Score.objects.filter(player=user))
            if nGames != 0:
                tmp['win_rate'] = nWins / nGames * 100
            else:
                tmp['win_rate'] = 0.0
            tmp['n_games'] = nGames
            winGames = Score.objects.filter(player=user,win=True)
            avrScore = 0
            if winGames.exists:
                for winGame in winGames:
                    avrScore = avrScore + winGame.score

                if winGames.count() != 0:
                    avrScore = avrScore / winGames.count()
                
            tmp['avr_score'] = avrScore
            if tmp['win_rate'] >= 80:
                tmp['best_user'] = True
            if tmp['win_rate'] <= 20:
                tmp['worst_user'] = True

            rank.append(tmp)
        sorted_rank = sorted(rank, key=(lambda x: -x['win_rate']))
        return sorted_rank



def create_game(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            logger = logging.getLogger('test')
            logger.error(request.POST)

            logger.error(request.POST.get('num_players'))
            num_player = int(request.POST.get('num_players'))
            game = Game(num_players=num_player)
            
            scores = []
            for i in range(1,num_player+1):
                player_set = User.objects.filter(username=request.POST.get('player_'+str(i)+'_name'))
                if player_set.exists():
                    player = player_set.get()
                else:
                    raise BadRequest
                intScore = request.POST.get('player_'+str(i)+'_score')
                if i % 2 == 1:
                    win = True
                else:
                    win = False
                
                scores.append(Score(game=game, player=player, score=intScore, win=win))
                #need validation
            game.save()
            for score in scores:
                score.save()
        return redirect('/')
    else:
        raise PermissionDenied

dashboard/templates/dashboard/game_form.html
{% load crispy_forms_tags %}
{% csrf_token %}

<div class="container">
    <div class="row mb-4">
        <div class="form-check mr-4">
            <input class="form-check-input" type="radio" onclick="createPlayerInputs(event)" name="num_players"
                id="flexRadioDefault1" value=2 checked>
            <label class="form-check-label" for="flexRadioDefault1">
                2인
            </label>
        </div>
        <div class="form-check mr-4">
            <input class="form-check-input" type="radio" onclick="createPlayerInputs(event)" name="num_players"
                id="flexRadioDefault2" value=3>
            <label class="form-check-label" for="flexRadioDefault2">
                3인
            </label>
        </div>
        <div class="form-check mr-4">
            <input class="form-check-input" type="radio" onclick="createPlayerInputs(event)" name="num_players"
                id="flexRadioDefault2" value=4>
            <label class="form-check-label" for="flexRadioDefault3">
                4인
            </label>
        </div>
    </div>
    <div id="player_inputs">
        <h5>Winner</h5>
        <hr>
        

        <div id="player_1" class="row mb-5">
            <select name="player_1_name" form="game-form" id="player_1" class="form-select">
                <option selected>플레이어 선택</option>
                {% for u in user_list %}
                <option value="{{u.username}}">{{u.first_name}}</option>
                {% endfor %}
            </select>
            <label for="player_1_score" class="form-label my-auto ml-4 mr-2">점수</label>
            <input name="player_1_score" type="range" value=100 class="form-range" onchange="showScore(this.id)" min=50
                max=400 step=10 id="player_1_score">
            <label for="player_1_score" class="form-label my-auto ml-4 mr-2 score" id="player_1_score_value">100</label>
            <button type="button" class="btn" value="player_1_score" onclick="incrementScore(event)">+</button>
            <button type="button" class="btn" value="player_1_score" onclick="decrementScore(event)">-</button>
        </div>

        <div id="player_3" class="row mb-5">
            <select name="player_3_name" form="game-form" id="player_1" class="form-select">
                <option selected>플레이어 선택</option>
                {% for u in user_list %}
                <option value="{{u.username}}">{{u.first_name}}</option>
                {% endfor %}
            </select>
            <label for="player_3_score" class="form-label my-auto ml-4 mr-2">점수</label>
            <input name="player_3_score" type="range" value=100 class="form-range" onchange="showScore(this.id)" min=50
                max=400 step=10 id="player_3_score">
            <label for="player_3_score" class="form-label my-auto ml-4 mr-2 score" id="player_3_score_value">100</label>
            <button type="button" class="btn" value="player_3_score" onclick="incrementScore(event)">+</button>
            <button type="button" class="btn" value="player_3_score" onclick="decrementScore(event)">-</button>
        </div>


        <h5>Loser</h5>
        <hr>



        <div id="player_2" class="row mb-5">
            <select name="player_2_name" form="game-form" id="player_2" class="form-select">
                <option selected>플레이어 선택</option>
                {% for u in user_list %}
                <option value="{{u.username}}">{{u.first_name}}</option>
                {% endfor %}
            </select>
            <label for="player_2_score" class="form-label my-auto ml-4 mr-2">점수</label>
            <input name="player_2_score" type="range" value=100 class="form-range" onchange="showScore(this.id)" min=50
                max=400 step=10 id="player_2_score">
            <label for="player_2_score" class="form-label my-auto ml-4 mr-2 score" id="player_2_score_value">100</label>
            <button type="button" class="btn" value="player_2_score" onclick="incrementScore(event)">+</button>
            <button type="button" class="btn" value="player_2_score" onclick="decrementScore(event)">-</button>
        </div>

        <div id="player_4" class="row mb-5">
            <select name="player_4_name" form="game-form" id="player_1" class="form-select">
                <option selected>플레이어 선택</option>
                {% for u in user_list %}
                <option value="{{u.username}}">{{u.first_name}}</option>
                {% endfor %}
            </select>
            <label for="player_4_score" class="form-label my-auto ml-4 mr-2">점수</label>
            <input name="player_4_score" type="range" value=100 class="form-range" onchange="showScore(this.id)" min=50
                max=400 step=10 id="player_4_score">
            <label for="player_4_score" class="form-label my-auto ml-4 mr-2 score" id="player_4_score_value">100</label>
            <button type="button" class="btn" value="player_4_score" onclick="incrementScore(event)">+</button>
            <button type="button" class="btn" value="player_4_score" onclick="decrementScore(event)">-</button>
        </div>
        <!-- </div> -->
    </div>
</div>





<!-- {% for i in "x"|rjust:"2" %}
        <div class="row mb-5">
            <select name="player[2]" form="game-form" id="player_2" class="form-select" aria-label="Default select example">
                <option selected>플레이어 선택</option>
                {% for u in user_list %}
                <option value="{{u}}">{{u}}</option>
                {% endfor %}
            </select>
            <label for="score_{{forloop.counter}}" class="form-label my-auto ml-4 mr-2">점수</label>
            <input name="score[{{forloop.counter}}]" type="range" value=100 class="form-range" onchange="showScore(this.id)" min=50
                max=400 step=10 id="score_2">
            <label for="score_{{forloop.counter}}" class="form-label my-auto ml-4 mr-2 score" id="score_2_value">100</label>
            <button type="button" class="btn" value="score_2" onclick="incrementScore(event)">+</button>
            <button type="button" class="btn" value="score_2" onclick="decrementScore(event)">-</button>
        </div>
        {% endfor %} -->

dashboard/templates/dashboard/game_list.html
{% extends 'forum/base.html' %}
{% load crispy_forms_tags %}

{% block main_area %}
<div class="container">
    <div class="row" style="min-height: 360px;">
        <div class="col">
            <h3 class="">유저보드</h3>
            <table class="table mb-auto" id="user-board">
                <thead>
                    <th class="col-1">#</th>
                    <th class="col-3">이름</th>
                    <th class="col-2">승률</th>
                    <th class="col-2">게임 수</th>
                    <th class="col-2">점수</th>
                </thead>

                {% for rank in rank_list %}
                {% if rank.best_user %}
                <tr class="table-success" id="rank_tr_{{ forloop.counter0 }}">
                    {% elif rank.worst_user %}
                <tr class="table-danger" id="rank_tr_{{ forloop.counter0 }}">
                    {% else %}
                <tr id="rank_tr_{{ forloop.counter0 }}">
                    {% endif %}
                    <td>{{ forloop.counter }}</td>
                    <td>{{ rank.name }}</td>
                    <td>{{ rank.win_rate }}</td>
                    <td>{{ rank.n_games }}</td>
                    <td>{{ rank.avr_score }}</td>
                </tr>

                {% endfor %}
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="float-right" id="rank-pagination"></div>
        </div>
    </div>
    <script>
        var n_games = {{ n_games }};

        var n_rank = {{ n_rank }};
    </script>

    <div class="row">
        <div class="col">
            <h3>전적</h3>
            <hr />
        </div>
    </div>
    <div class="row">
        <div class="col">
            <a role="button" class="btn btn-outline-dark btn-block btn-sm" href="#" data-toggle="modal"
                data-target="#createGameModal">새 기록 입력하기</a>
        </div>
    </div>
    <div class="row" style="min-height: 330px;">
        <div class="col">
            <table class="table mb-4">
                <thead>
                    <tr>
                        <th class="col-2">날짜</th>
                        <th class="col-3">승</th>
                        <th class="col-3">패</th>
                        <th class="col-4">점수</th>
                    </tr>
                </thead>
                <tbody>
                    {% for game in game_list %}
                    <tr id="game_tr_{{ forloop.counter0 }}">
                        <td>{{game.played_at.date | date:'Y/m/d'}}</td>
                        <td>
                            {% for score in game.score_set.iterator %}
                            {% if score.win %}
                            {{score.player.first_name}}
                            {% endif %}
                            {% endfor %}
                        </td>
                        <td>
                            {% for score in game.score_set.iterator %}
                            {% if not score.win %}
                            {{score.player.first_name}}
                            {% endif %}
                            {% endfor %}
                        </td>
                        <td>
                            {% for score in game.score_set.iterator %}

                            {{score.score}}
                            {% if not forloop.last %}
                            &nbsp; / &nbsp;
                            {% endif %}
                            {% endfor %}
                        </td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div id="game-pagination"></div>

</div>

<div class="modal fade" id="createGameModal" tabindex="-1" aria-labelledby="createGameModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createGameModalLabel">기록 작성</h5>
                <button type="button" class="btn-close" data-dismiss="modal" aria-label="Close"></button>
            </div>

            <form id="game-form" method="POST" action="/create_game/">
                {%csrf_token %}
                <div class="modal-body">
                    {% include "dashboard/game_form.html" %}
                </div>

                <div class="modal-footer">
                    <button type="submit" class="btn btn-secondary">제출하기</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">닫기</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}


<!-- <nav aria-label='...'>
    <ul class='pagination pagination-sm'>
        <li class='page-item'>
            < class='page-link' onclick='game_pagination(event)'>1</a>
        </li>
    </ul>
</nav> -->